export const ACCIDENT_DOCUMENT_TYPES = [
  { value: 'RELATORIO_CONCLUSAO_ACIDENTE', label: 'Relatório de Conclusão' },
  { value: 'FICHA_INVESTIGACAO_ACIDENTE', label: 'Ficha de Investigação' },
  { value: 'COMUNICADO_ACIDENTE', label: 'Comunicado de Acidente' },
] as const

export const ACCIDENT_DOCUMENT_TYPE_LABELS = Object.fromEntries(
  ACCIDENT_DOCUMENT_TYPES.map((item) => [item.value, item.label]),
) as Record<string, string>

export const ACCIDENT_TEMPLATE_VARIABLES = [
  'codigo_acidente',
  'empresa',
  'cnpj_empresa',
  'unidade',
  'nome',
  'colaborador',
  'cpf',
  'matricula',
  'funcao',
  'data_ocorrencia',
  'hora_ocorrencia',
  'data_registro',
  'hora_registro',
  'local',
  'tipo_acidente',
  'gravidade',
  'status',
  'descricao_acidente',
  'parte_atingida',
  'atendimento_medico',
  'afastamento',
  'dias_afastamento',
  'cat_emitida',
  'numero_cat',
  'testemunhas',
  'acoes_imediatas',
  'investigador',
  'data_inicio_investigacao',
  'causa_imediata',
  'causa_raiz',
  'fatores_contribuintes',
  'acoes_corretivas',
  'medidas_preventivas',
  'notas_gestao',
  'recomendacoes',
  'conclusao',
  'data_encerramento',
  'data_emissao',
]
